/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Luthfan
 */
public class tiket extends javax.swing.JFrame {

    /**
     * Creates new form tikrt
     */
    public tiket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbmdestinasi1 = new javax.swing.JComboBox<>();
        txtnopenerbangan1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        rbekonomi1 = new javax.swing.JRadioButton();
        rbbisnis1 = new javax.swing.JRadioButton();
        rbfristclass1 = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        txtharga1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtmaskapai1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txttanggal1 = new javax.swing.JTextField();
        txtjam1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtnama1 = new javax.swing.JTextField();
        txtnoidentitas1 = new javax.swing.JTextField();
        txtjumlah1 = new javax.swing.JTextField();
        txttotalharga1 = new javax.swing.JTextField();
        txtbayar1 = new javax.swing.JTextField();
        txtkembalian1 = new javax.swing.JTextField();
        btnbelilagi1 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        btnbeli1 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbbeli = new javax.swing.JTable();
        bthapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 255, 204));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MingLiU-ExtB", 1, 18)); // NOI18N
        jLabel1.setText("PEMESANAN TIKET  PESAWAT SSS-AIR");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "MASKAPAI"));

        jLabel21.setText("DESTINASI");

        jLabel22.setText("NAMA MASKAPAI");

        jLabel23.setText("NO.PENERBANGAN");

        cbmdestinasi1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "===PILIH===", "JAKARTA - PONTIANAK", "PONTIANAK - JAKARTA", "PONTIANAK - BANDUNG", "BANDUNG - PONTIANAK", "JAKARTA - SURABAYA", "PONTIANAK - MEDAN", "PALEMBANG - PONTIANAK", " ", " " }));
        cbmdestinasi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmdestinasi1ActionPerformed(evt);
            }
        });

        jLabel24.setText("KELAS");

        rbekonomi1.setBackground(new java.awt.Color(51, 255, 204));
        rbekonomi1.setText("EKONOMI");
        rbekonomi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbekonomi1ActionPerformed(evt);
            }
        });

        rbbisnis1.setBackground(new java.awt.Color(51, 255, 204));
        rbbisnis1.setText("BISNIS");
        rbbisnis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbisnis1ActionPerformed(evt);
            }
        });

        rbfristclass1.setBackground(new java.awt.Color(51, 255, 204));
        rbfristclass1.setText("FIRST CLASS");
        rbfristclass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfristclass1ActionPerformed(evt);
            }
        });

        jLabel25.setText("HARGA");

        txtharga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtharga1ActionPerformed(evt);
            }
        });

        jLabel26.setText("Rp.");

        jLabel27.setText("TANGGAL KEBERANGKATAN");

        jLabel28.setText("JAM KEBERANGKATAN");

        jLabel29.setText("WIB");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel27)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtharga1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel28)
                            .addComponent(jLabel24))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbekonomi1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtjam1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29))
                            .addComponent(cbmdestinasi1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnopenerbangan1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbbisnis1)
                            .addComponent(rbfristclass1)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txttanggal1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtmaskapai1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(cbmdestinasi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtmaskapai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtnopenerbangan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txttanggal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtjam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbekonomi1)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbbisnis1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbfristclass1)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(txtharga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 370, 370));

        jPanel5.setBackground(new java.awt.Color(0, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "PEMESANAN"));

        jLabel30.setText("NAMA");

        jLabel31.setText("NO.IDENTITAS");

        jLabel32.setText("JUMLAH");

        jLabel33.setText("TOTAL HARGA");

        jLabel34.setText("UANG BAYAR");

        jLabel35.setText("UANG KEMBALI");

        txtnama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnama1ActionPerformed(evt);
            }
        });
        txtnama1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnama1KeyTyped(evt);
            }
        });

        txtnoidentitas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoidentitas1ActionPerformed(evt);
            }
        });
        txtnoidentitas1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnoidentitas1KeyTyped(evt);
            }
        });

        txtjumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah1ActionPerformed(evt);
            }
        });
        txtjumlah1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjumlah1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtjumlah1KeyTyped(evt);
            }
        });

        txttotalharga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalharga1ActionPerformed(evt);
            }
        });

        txtbayar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayar1ActionPerformed(evt);
            }
        });
        txtbayar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbayar1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbayar1KeyTyped(evt);
            }
        });

        txtkembalian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembalian1ActionPerformed(evt);
            }
        });
        txtkembalian1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkembalian1KeyReleased(evt);
            }
        });

        btnbelilagi1.setText("REFRESH");
        btnbelilagi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbelilagi1ActionPerformed(evt);
            }
        });

        jLabel36.setText("TIKET");

        btnbeli1.setText("BELI");
        btnbeli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeli1ActionPerformed(evt);
            }
        });

        jLabel37.setText("Rp.");

        jLabel38.setText("Rp.");

        jLabel39.setText("Rp.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel34)
                            .addComponent(jLabel30)
                            .addComponent(jLabel33)
                            .addComponent(jLabel35))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtkembalian1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(txtnoidentitas1)
                                    .addComponent(txtnama1))
                                .addGap(33, 33, 33))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(txtjumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel36))
                                            .addComponent(txttotalharga1)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtbayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnbeli1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnbelilagi1)
                        .addGap(78, 78, 78))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtnama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtnoidentitas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtjumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txttotalharga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbayar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkembalian1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbeli1)
                    .addComponent(btnbelilagi1))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 370, 360));

        tbbeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NAMA", "NO.IDENTITAS", "NAMA MASKAPAI", "NO.PENERBANGAN", "DESTINASI", "TANGGAL KEBERANGKATAN", "JAM KEBERANGKATAN"
            }
        ));
        jScrollPane3.setViewportView(tbbeli);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 870, 120));

        bthapus.setText("HAPUS DATA");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        jPanel2.add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 140, -1));

        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel2.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 620, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbmdestinasi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmdestinasi1ActionPerformed
        // TODO add your handling code here:
         if(cbmdestinasi.getSelectedItem().equals("===PILIH===")){
            buttonGroup1.clearSelection();
            txtmaskapai.setText("");
            txtnopenerbangan.setText("");
            txtharga.setText("");
        }
        else if(cbmdestinasi.getSelectedItem().equals("JAKARTA - PONTIANAK")){
            txtmaskapai.setText("GARUDA INDONESIA");
            txtnopenerbangan.setText("09-GA890");
            txttanggal.setText("6 MAI 2020");
            txtjam.setText("13:40");
            ekonomi=1450000;
            bisnis=1560000;
            frist=2125000;
        }
        else if(cbmdestinasi.getSelectedItem().equals("PONTIANAK - JAKARTA")){
            txtmaskapai.setText("GARUDA INDONESIA");
            txtnopenerbangan.setText("09-GA890");
            txttanggal.setText("1 JUNI 2020");
            txtjam.setText("11:40");
            ekonomi=1400000;
            bisnis=1450000;
            frist=1865000;
        }
        else if(cbmdestinasi.getSelectedItem().equals("PONTIANAK - BANDUNG")){
            txtmaskapai.setText("BATIK AIR");
            txtnopenerbangan.setText("03-BA770");
            txttanggal.setText("13 JUNI 2020");
            txtjam.setText("08:10");
            ekonomi=1500000;
            bisnis=2000000;
            frist=2500000;
        }
        else if(cbmdestinasi.getSelectedItem().equals("BANDUNG - PONTIANAK")){
            txtmaskapai.setText("SRIWIJAYA AIR");
            txtnopenerbangan.setText("01-SJ554");
            txttanggal.setText("10 JUNI 2020");
            txtjam.setText("09:10");
            ekonomi=800000;
            bisnis=1550000;
            frist=1850000;
        }
        else if(cbmdestinasi.getSelectedItem().equals("JAKARTA - SURABAYA")){
            txtmaskapai.setText("BATIK AIR");
            txtnopenerbangan.setText("03-BA870");
            txttanggal.setText("19 JULI 2020");
            txtjam.setText("15:30");
            ekonomi=1700000;
            bisnis=1950000;
            frist=2150000;
        }
        else if(cbmdestinasi.getSelectedItem().equals("PONTIANAK - MEDAN")){
            txtmaskapai.setText("LION AIR");
            txtnopenerbangan.setText("09-LN871");
            txttanggal.setText("17 JUNI 2020");
            txtjam.setText("13:40");
            ekonomi=1550000;
            bisnis=1950000;
            frist=2150000;
        }
        else if(cbmdestinasi.getSelectedItem().equals("PALEMBANG - PONTIANAK")){
            txtmaskapai.setText("SRIWIJAYA AIR");
            txtnopenerbangan.setText("01-SJ765");
            txttanggal.setText("3 JUNI 2020");
            txtjam.setText("19:40");
            ekonomi=1558000;
            bisnis=2100000;
            frist=2585000;
        }

    }//GEN-LAST:event_cbmdestinasi1ActionPerformed

    private void rbekonomi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbekonomi1ActionPerformed
        // TODO add your handling code here:
        if(rbekonomi.isSelected()){
            txtharga.setText(String.valueOf(ekonomi));
            rbbisnis.setSelected(false);
            rbfristclass.setSelected(false);
        }
    }//GEN-LAST:event_rbekonomi1ActionPerformed

    private void rbbisnis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbisnis1ActionPerformed
        // TODO add your handling code here:
        if(rbbisnis.isSelected()){
            txtharga.setText(String.valueOf(bisnis));
            rbekonomi.setSelected(false);
            rbfristclass.setSelected(false);
        }

    }//GEN-LAST:event_rbbisnis1ActionPerformed

    private void rbfristclass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfristclass1ActionPerformed
        // TODO add your handling code here:
        if(rbfristclass.isSelected()){
            txtharga.setText(String.valueOf(frist));
            rbekonomi.setSelected(false);
            rbbisnis.setSelected(false);{

            }
        }
    }//GEN-LAST:event_rbfristclass1ActionPerformed

    private void txtharga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtharga1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtharga1ActionPerformed

    private void txtnama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnama1ActionPerformed

    private void txtnama1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnama1KeyTyped
        // TODO add your handling code here:
        char x = evt.getKeyChar();
        if ((Character.isDigit(x) || x == KeyEvent.VK_BACK_SPACE || x == KeyEvent.VK_DELETE )){
            evt.consume();
        }
    }//GEN-LAST:event_txtnama1KeyTyped

    private void txtnoidentitas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoidentitas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoidentitas1ActionPerformed

    private void txtnoidentitas1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnoidentitas1KeyTyped
        // TODO add your handling code here:||
        char x = evt.getKeyChar();
        if (!(Character.isDigit(x) || x == KeyEvent.VK_BACK_SPACE || x == KeyEvent.VK_DELETE )){
            evt.consume();
        }
    }//GEN-LAST:event_txtnoidentitas1KeyTyped

    private void txtjumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah1ActionPerformed
        // TODO add your handling code here:
        beli=Integer.parseInt(txtjumlah.getText());
        harga=Integer.parseInt(txtharga.getText());
        total=bayar*harga;
        txttotalharga.setText(String.valueOf(total));
    }//GEN-LAST:event_txtjumlah1ActionPerformed

    private void txtjumlah1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlah1KeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a=Integer.valueOf(txtharga.getText());
        b=Integer.valueOf(txtjumlah.getText());
        c=a*b;
        txttotalharga.setText(""+c);
    }//GEN-LAST:event_txtjumlah1KeyReleased

    private void txtjumlah1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlah1KeyTyped
        // TODO add your handling code here:
        char x = evt.getKeyChar();
        if (!(Character.isDigit(x) || x == KeyEvent.VK_BACK_SPACE || x == KeyEvent.VK_DELETE )){
            evt.consume();
        }
    }//GEN-LAST:event_txtjumlah1KeyTyped

    private void txttotalharga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalharga1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txttotalharga1ActionPerformed

    private void txtbayar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayar1ActionPerformed
        // TODO add your handling code here:
        beli=Integer.parseInt(txtbayar.getText());
        kembali=Integer.parseInt(txttotalharga.getText());
        total=bayar-kembali;
        txtkembalian.setText(String.valueOf(total));
    }//GEN-LAST:event_txtbayar1ActionPerformed

    private void txtbayar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayar1KeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a=Integer.valueOf(txtbayar.getText());
        b=Integer.valueOf(txttotalharga.getText());
        c=a-b;
        txtkembalian.setText(""+c);
    }//GEN-LAST:event_txtbayar1KeyReleased

    private void txtbayar1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayar1KeyTyped
        // TODO add your handling code here:
        char x = evt.getKeyChar();
        if (!(Character.isDigit(x) || x == KeyEvent.VK_BACK_SPACE || x == KeyEvent.VK_DELETE )){
            evt.consume();
        }
    }//GEN-LAST:event_txtbayar1KeyTyped

    private void txtkembalian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembalian1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkembalian1ActionPerformed

    private void txtkembalian1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkembalian1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkembalian1KeyReleased

    private void btnbelilagi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbelilagi1ActionPerformed
        // TODO add your handling code here:
        cbmdestinasi.setSelectedItem("===PILIH===");
        rbekonomi.setSelected(false);
        rbbisnis.setSelected(false);
        rbfristclass.setSelected(false);
        txtmaskapai.setText("");
        txtnopenerbangan.setText("");
        txttanggal.setText("");
        txtjam.setText("");
        txtharga.setText("");
        txtnama.setText("");
        txtnoidentitas.setText("");
        txtjumlah.setText("");
        txttotalharga.setText("");
        txtbayar.setText("");
        txtkembalian.setText("");
    }//GEN-LAST:event_btnbelilagi1ActionPerformed

    private void btnbeli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeli1ActionPerformed

        tbbeli.setValueAt(txtnama.getText(),x,0);
        tbbeli.setValueAt(txtnoidentitas.getText(),x,1);
        tbbeli.setValueAt(txtmaskapai.getText(),x,2);
        tbbeli.setValueAt(txtnopenerbangan.getText(),x,3);
        tbbeli.setValueAt(cbmdestinasi.getSelectedItem(),x,4);
        tbbeli.setValueAt(txttanggal.getText(),x,5);
        tbbeli.setValueAt(txtjam.getText(),x,6);
        x=x+1;
    }//GEN-LAST:event_btnbeli1ActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        tbbeli.setValueAt("", tbbeli.getSelectedRow(), 0);
        tbbeli.setValueAt("", tbbeli.getSelectedRow(), 1);
        tbbeli.setValueAt("", tbbeli.getSelectedRow(), 2);
        tbbeli.setValueAt("", tbbeli.getSelectedRow(), 3);
        tbbeli.setValueAt("", tbbeli.getSelectedRow(), 4);
        tbbeli.setValueAt("", tbbeli.getSelectedRow(), 5);
        tbbeli.setValueAt("", tbbeli.getSelectedRow(), 6);
    }//GEN-LAST:event_bthapusActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:

        int jawab= JOptionPane.showConfirmDialog(null, "APAKAH ANDA INGIN KELUAR","KELUAR", JOptionPane.OK_OPTION);
        if(jawab==JOptionPane.OK_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btnbeli1;
    private javax.swing.JButton btnbelilagi1;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JComboBox<String> cbmdestinasi1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbbisnis1;
    private javax.swing.JRadioButton rbekonomi1;
    private javax.swing.JRadioButton rbfristclass1;
    private javax.swing.JTable tbbeli;
    private javax.swing.JTextField txtbayar1;
    private javax.swing.JTextField txtharga1;
    private javax.swing.JTextField txtjam1;
    private javax.swing.JTextField txtjumlah1;
    private javax.swing.JTextField txtkembalian1;
    private javax.swing.JTextField txtmaskapai1;
    private javax.swing.JTextField txtnama1;
    private javax.swing.JTextField txtnoidentitas1;
    private javax.swing.JTextField txtnopenerbangan1;
    private javax.swing.JTextField txttanggal1;
    private javax.swing.JTextField txttotalharga1;
    // End of variables declaration//GEN-END:variables
}
